<script type="text/javascript" data-breeze>
    require(['jquery'], function ($) {
        const highlightList = $('.widget.block-highlight .products.list > li');
        const productList = $('.widget.block-products-list .product-items > li');
        const combinedList = [...highlightList, ...productList];

        if (combinedList.length === 0) return;

        combinedList.forEach(item => {
            $(item).find('.action.tocompare').remove();
        });
    });
</script>