<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\Compare\ListCompare */
?>
<?php

$total = $block->getItems()->getSize();
$compare = $this->helper('Magento\Catalog\Helper\Product\Compare');
$output = $this->helper('Magento\Catalog\Helper\Output');
$isAllow = $this->helper('Magento\Wishlist\Helper\Data')->isAllow();
$showAttributesLabels = $this->helper('Swissup\Compare\Helper\Data')->showAttributesLabels();
$isStickyHeader = $this->helper('Swissup\Compare\Helper\Data')->isStickyEnabled();
$stickyHeaderId = 'sticky-header-off';
if ($isStickyHeader) {
    $stickyHeaderId = 'sticky-header-on';
}
?>
<?php if ($total): ?>
    <div class="actions comparison">
        <?php if (!$showAttributesLabels && $total > 1): ?>
        <span class="action differences">
            <input class="btn_diff" id="icon-btn_differences" type="checkbox" name="btn_differences" />
            <label data-icon-off="<?= $block->escapeHtml(__('All')) ?>" data-icon-on="<?= $block->escapeHtml(__('Diff')) ?>" for="icon-btn_differences"></label>
        </span>
        <?php endif; ?>
        <a class="action go-back" href="#/" onclick="history.go(-1); return false;" title="<?= /* @escapeNotVerified */ __('Add new product') ?>">
            <span><?= /* @escapeNotVerified */ __('Add new product') ?></span>
        </a>
        <a class="action print hidden-print" href="#/" title="<?= /* @escapeNotVerified */ __('Print This Page') ?>">
            <span><?= /* @escapeNotVerified */ __('Print This Page') ?></span>
        </a>
    </div>
    <div id="<?= $stickyHeaderId ?>" class="table-wrapper comparison" data-mage-init='{"Swissup_Compare/js/compare": {"table": ".table-comparison", "windowPrintSelector":".action.print"}}'>
        <table class="data table table-comparison" id="product-comparison">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Compare Products') ?></caption>
            <thead>
            <tr>
                <?php $index = 0; ?>
                <?php foreach ($block->getItems() as $item): ?>
                    <?php if ($showAttributesLabels && $index++ == 0): ?>
                        <th scope="row" class="cell label remove">
                            <span><?= /* @escapeNotVerified */ __('Remove Product') ?></span>
                        </th>
                    <?php endif; ?>
                    <td class="cell remove product hidden-print">
                        <a href="#" data-post='<?= /* @escapeNotVerified */ $compare->getPostDataRemove($item) ?>'
                           class="action delete" title="<?= /* @escapeNotVerified */ __('Remove Product') ?>">
                            <span><?= /* @escapeNotVerified */ __('Remove Product') ?></span>
                        </a>
                    </td>
                <?php endforeach; ?>
            </tr>
            <tr>
                <?php if ($showAttributesLabels): ?>
                    <?php if ($total > 1): ?>
                        <th scope="row" class="cell label product">
                            <input class="tgl tgl-flip" id="cb5" type="checkbox" name="btn_differences" />
                            <label class="tgl-btn" data-tg-off="<?= $block->escapeHtml(__('Show All')) ?>" data-tg-on="<?= $block->escapeHtml(__('Show Differences')) ?>" for="cb5"></label>
                        </th>
                    <?php else : ?>
                        <th scope="row" class="cell label product"></th>
                    <?php endif; ?>
                <?php endif; ?>

                <?php foreach ($block->getItems() as $item): ?>
                    <td data-th="<?= $block->escapeHtml(__('Product')) ?>" class="cell product info">
                        <a class="product-item-photo" href="<?= /* @escapeNotVerified */ $block->getProductUrl($item) ?>" title="<?= /* @escapeNotVerified */ $block->stripTags($item->getName(), null, true) ?>">
                            <?= $block->getImage($item, 'product_comparison_list')->toHtml() ?>
                        </a>
                        <strong class="product-item-name">
                            <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($item) ?>" title="<?= /* @escapeNotVerified */ $block->stripTags($item->getName(), null, true) ?>">
                                <?= /* @escapeNotVerified */ $output->productAttribute($item, $item->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($item, 'short') ?>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($item, '-compare-list-top') ?>
                        <div class="product-item-actions hidden-print">
                            <div class="actions-primary">
                                <?php if ($item->isSaleable()): ?>
                                    <form data-role="tocart-form" action="<?= /* @escapeNotVerified */ $compare->getAddToCartUrl($item) ?>" method="post">
                                        <?= $block->getBlockHtml('formkey') ?>
                                        <button type="submit" class="action tocart primary">
                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                        </button>
                                    </form>
                                <?php else: ?>
                                    <?php if ($item->getIsSalable()): ?>
                                        <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                    <?php else: ?>
                                        <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                            <?php if ($isAllow) : ?>
                                <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                    <a href="#" data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($item) ?>' class="action towishlist" data-action="add-to-wishlist">
                                        <span><?= /* @escapeNotVerified */ __('Add to Wish List') ?></span>
                                    </a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </td>
                <?php endforeach; ?>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($block->getAttributes() as $attribute): ?>
                <?php $index = 0 ?>
                <tr>
                    <?php foreach ($block->getItems() as $item): ?>
                        <?php if ($showAttributesLabels && $index++ == 0): ?>
                            <th scope="row" class="cell label">
                                <span class="attribute label">
                                    <?= $block->escapeHtml($attribute->getStoreLabel() ? $attribute->getStoreLabel() : __($attribute->getFrontendLabel())) ?>
                                </span>
                            </th>
                        <?php endif; ?>
                        <td class="cell product attribute">
                            <div class="attribute value">
                                <?php switch ($attribute->getAttributeCode()) {
                                    case "price": ?>
                                        <?php
                                            /* @escapeNotVerified */ echo $block->getProductPrice(
                                                $item,
                                                '-compare-list-' . $attribute->getCode()
                                            )
                                        ?>
                                        <?php break;
                                    case "small_image": ?>
                                        <?php $block->getImage($item, 'product_small_image')->toHtml(); ?>
                                        <?php break;
                                    default: ?>
                                        <?php $value = (string) $block->getProductAttributeValue($item, $attribute); ?>
                                        <?php if (!empty($value)) : ?>
                                            <?= /* @escapeNotVerified */ $output->productAttribute($item, $value, $attribute->getAttributeCode()) ?>
                                        <?php else : ?>
                                            <span><?= /* @escapeNotVerified */ __('N/A') ?></span>
                                        <?php endif ?>
                                    <?php break;
                                } ?>
                            </div>
                        </td>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form]": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php else: ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('You have no items to compare.') ?></div></div>
<?php endif; ?>
